name: ml4ff_env
channels:
  - defaults
dependencies:
  - python=3.10.12
  - pip
  - numpy
  - pandas
  - psutil
  - openpyxl
  - scipy
  - scikit-learn
  - lightgbm
  - xgboost
  - pytorch
  - pip:
      - skorch
      - git+https://github.com/hyperopt/hyperopt-sklearn