name: ml4ff_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.11
  - pip
  - numpy
  - pandas
  - psutil
  - openpyxl
  - scipy
  - scikit-learn
  - lightgbm
  - xgboost=2.1.4
  - pytorch
  - pip:
      - skorch
      - git+https://github.com/hyperopt/hyperopt-sklearn